name: Gradle CI

on:
    push:
        branches:
            - master

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Java JDK 8
              uses: actions/setup-java@v3
              with:
                  java-version: '8'
                  distribution: 'temurin'

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 7.4.2

            - name: uberJar with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: jvm:uberJar

            - name: Upload JVM
              uses: actions/upload-artifact@v2
              with:
                  name: jvm-package
                  path: jvm/build/libs/

            - name: linkReleaseExecutableNative with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: native:linkReleaseExecutableNative
              env:
                USERNAME: ${{ secrets.USERNAME }}
                TOKEN: ${{ secrets.TOKEN }}

            - name: Upload Native
              uses: actions/upload-artifact@v2
              with:
                  name: native-package-win
                  path: native/build/bin/native/releaseExecutable

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Java JDK 8
              uses: actions/setup-java@v3
              with:
                  java-version: '8'
                  distribution: 'temurin'

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 7.4.2

            - name: linkReleaseExecutableNative with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: native:linkReleaseExecutableNative
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  TOKEN: ${{ secrets.TOKEN }}

            - name: Upload Native
              uses: actions/upload-artifact@v2
              with:
                  name: native-package-win
                  path: native/build/bin/native/releaseExecutable
